openapi: 3.0.0
info:
  version: 1.0.0
  title: Cancun Hotel API
  description: API used to manage guests, rooms and reservations for the last Cancun Hotel
  contact:
    email: "apiteam@swagger.io"
paths:
  /api:
    get:
      tags:
        - Hello
      description: Returns hello in specified language
      parameters:
        - in: query
          name: lang
          required: true
          description: language
          schema:
            type: string
            example: es

      responses:
        '200':
          description: hello in the requested language
          content:
            text/plain:
              schema:
                type: string
                example: hola